### ISSUE TITLE
Error while trying to reach light 

### ISSUE THREAD

**Issue by Mindstormsnxt** [diyhue/Lights#40]
Hi, 

when trying to turn on/off new "Generic Dimmable" Lights, I'm getting this error:

`10.0.0.8 - - [21/Apr/2019 18:03:22] "PUT /api/a7161538be80d40b3de98dece6e91f90/lights/11/state HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('10.0.0.8', 50592)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "./HueEmulator3.py", line 1454, in do_PUT
    updateGroupStats(url_pices[4], bridge_config["lights"], bridge_config["groups"])
  File "/opt/hue-emulator/functions/updateGroup.py", line 10, in updateGroupStats
    if lights[group_light]["state"]["on"]:
KeyError: '14'
`

What could this mean? The light isn't responding, but can be controlled via its own ip address...
Deleting the mac from the config file also doesn't seem to help :/

Also, when uploading the newest Generic CCT Light sketch with deleting all eeprom settings, the wifimanager hosts just a standard-named Wifi (ESP-CD5R), instead of using the actually defined light name. Reinstalling the library doesn't work.

Any suggestions?

**Comment by mariusmotea** [comment]
When you flash the esp set some SPIFFS storage from Arduino. This is the place where light config must be placed. If everything is ok the ssid will be something with Hue Lightg.....

**Comment by Mindstormsnxt** [comment]
Thanks!
